name: "GitHub Package Operation"
description: "Operation GitHub Package with gh-pkg-cli"
author: "mekka<chmikata@gmail.com>"
inputs:
  command:
    description: "Command to run"
    required: true
  org:
    description: "Organization name"
    required: true
  matcher:
    description: "Matcher package name"
    required: true
  pattern:
    description: "Pattern sem or sha"
    required: false
    default: "sem"
  depth:
    description: "Tag search depth"
    required: false
    default: "0"
  token:
    description: "GitHub Token"
    required: false
    default: "${{ github.token }}"
outputs:
  package:
    description: "Package names"
  tag:
    description: "Tag names"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "-c ${{ inputs.command }}"
    - "-o ${{ inputs.org }}"
    - "-t ${{ inputs.token }}"
    - "-m ${{ inputs.matcher }}"
    - "-p ${{ inputs.pattern }}"
    - "-d ${{ inputs.depth }}"
