name: "GitHub Package Operation"
description: "Operation GitHub Package with gh-pkg-cli"
author: "mekka<chmikata@gmail.com>"
inputs:
  command:
    description: "Command to run"
    required: true
  org:
    description: "Organization name"
    required: true
  token:
    description: "Personal Access Token"
    required: true
  matcher:
    description: "Matcher package name"
    required: false
    default: ".*"
  pattern:
    description: "Pattern sem or sha"
    required: false
    default: "sem"
  depth:
    description: "Tag search depth"
    required: false
    default: "0"
  range:
    description: "Package major or minor or all"
    required: false
    default: "all"
outputs:
  result:
    description: "Output result"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "-c ${{ inputs.command }}"
    - "-o ${{ inputs.org }}"
    - "-t ${{ inputs.token }}"
    - "-m ${{ inputs.matcher }}"
    - "-p ${{ inputs.pattern }}"
    - "-d ${{ inputs.depth }}"
    - "-r ${{ inputs.range }}"
